export function insertSearchPane(elements) {
    return {
        bordered: ``,
        buttonGroup: `flex flex-row ${elements.spacing.gap} items-center`,
        buttonSub: `dtsp-buttonSub`,
        caret: ``,
        clear: `dtsp-clear`,
        clearAll: `dtsp-clearAll`,
        clearButton: `dtsp-clear-button`,
        collapseAll: `dtsp-collapseAll`,
        collapseButton: `dtsp-collapse-button`,
        container: `dtsp-searchPane flex flex-col ${elements.spacing.gap}`,
        countButton: `dtsp-countButton`,
        disabledButton: `!cursor-not-allowed opacity-25`,
        hidden: `dtsp-hidden`,
        hide: `dtsp-hide`,
        layout: `dtsp-`,
        name: `dtsp-name`,
        nameButton: `dtsp-nameButton`,
        nameCont: `dtsp-nameCont truncate`,
        narrow: `dtsp-narrow`,
        paneButton: `${elements.forms.button.alternative} h-full`,
        paneInputButton: ``,
        pill: `bg-primary-100 text-primary-800 text-xs font-medium px-2.5 py-0.5 rounded-full dark:bg-primary-900 dark:text-primary-300`,
        rotated: `dtsp-rotated`,
        search: `${elements.forms.search}`,
        searchCont: `flex flex-row w-full ${elements.spacing.gap}`,
        searchIcon: `dtsp-search`,
        searchLabelCont: `dtsp-searchButtonCont`,
        selected: `dtsp-selected`,
        smallGap: `dtsp-smallGap`,
        subRow1: `grow`,
        subRow2: `dtsp-subRow2`,
        subRowsContainer: `${elements.spacing.gap}`,
        title: `dtsp-title`,
        topRow: `flex flex-row`,
    };
}
